-- |
-- Module      : HumanoidAnim.IK.Core
-- Description : IK solver core types and interfaces
--
-- This module defines the core types and type class for Inverse Kinematics
-- solvers used in humanoid animation.
module HumanoidAnim.IK.Core
  ( -- * Constraints
    IKConstraint(..)
  , constraintBone
  , constraintPosition
  , constraintRotation

    -- * Input/Output
  , IKInput(..)
  , IKOutput(..)
  , IKWarning(..)

    -- * Solver Type
  , SolverType(..)
  ) where

import Data.Map.Strict (Map)
import Linear (V3(..), Quaternion(..))

import HumanoidAnim.Skeleton.Bones (HumanoidBone)
import HumanoidAnim.Skeleton.Config (Skeleton)

-- | IK constraint types
data IKConstraint
  = Fixed HumanoidBone (V3 Float)
    -- ^ Fixed bone at position (anchor point)
  | FixedWithRotation HumanoidBone (V3 Float) (Quaternion Float)
    -- ^ Fixed bone at position with fixed rotation (anchor point with orientation)
  | Effector HumanoidBone (V3 Float)
    -- ^ Effector bone target position
  | EffectorWithRotation HumanoidBone (V3 Float) (Quaternion Float)
    -- ^ Effector with both position and rotation target
  deriving stock (Show, Eq)

-- | Get the bone from a constraint
constraintBone :: IKConstraint -> HumanoidBone
constraintBone (Fixed bone _) = bone
constraintBone (FixedWithRotation bone _ _) = bone
constraintBone (Effector bone _) = bone
constraintBone (EffectorWithRotation bone _ _) = bone

-- | Get the target position from a constraint
constraintPosition :: IKConstraint -> V3 Float
constraintPosition (Fixed _ pos) = pos
constraintPosition (FixedWithRotation _ pos _) = pos
constraintPosition (Effector _ pos) = pos
constraintPosition (EffectorWithRotation _ pos _) = pos

-- | Get the target rotation from a constraint (if specified)
constraintRotation :: IKConstraint -> Maybe (Quaternion Float)
constraintRotation (Fixed _ _) = Nothing
constraintRotation (FixedWithRotation _ _ rot) = Just rot
constraintRotation (Effector _ _) = Nothing
constraintRotation (EffectorWithRotation _ _ rot) = Just rot

-- | Input for IK solver
data IKInput = IKInput
  { ikSkeleton :: Skeleton
    -- ^ Skeleton structure
  , ikInitialPose :: Map HumanoidBone (V3 Float)
    -- ^ Initial bone positions
  , ikConstraints :: [IKConstraint]
    -- ^ List of constraints to satisfy
  } deriving stock (Show)

-- | Output from IK solver
data IKOutput = IKOutput
  { ikResultPose :: Map HumanoidBone (V3 Float)
    -- ^ Resulting bone positions
  , ikIterations :: Int
    -- ^ Number of iterations performed
  , ikConverged :: Bool
    -- ^ Whether the solver converged within tolerance
  , ikError :: Float
    -- ^ Final error distance
  , ikWarnings :: [IKWarning]
    -- ^ Any warnings generated during solving
  } deriving stock (Show)

-- | Warnings generated by IK solver
data IKWarning
  = UnreachableTarget HumanoidBone Float
    -- ^ Target is unreachable, distance exceeded by amount
  | DidNotConverge Int Float
    -- ^ Did not converge within max iterations, final error
  deriving stock (Show, Eq)

-- | Solver type enumeration
data SolverType = FABRIKSolver | CCDSolver | TwoBoneSolver
  deriving stock (Show, Eq, Read)
